name: Dragonfruit
favicon: null
layout_spectrum: 0.83979
typography_spectrum: 0.21172
title: Dragonfruit Event Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1014'
    - '#b9d0d8'
    - '#7799a2'
    - '#bb4e31'
    - '#3a4b52'
  brandStrength: 0
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
