name: Dragonfruit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43693
title: Dragonfruit Event Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd5360'
    - '#c20f0b'
    - '#1b1a20'
    - '#d1f8c1'
    - '#8daf68'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
